# Generated by Django 4.2.4 on 2023-09-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_myorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myorders',
            old_name='added_date',
            new_name='order_date',
        ),
    ]
